spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: research
          uri: lb://research
          predicates:
            - Path=/users/**, /theatre/**
server:
  port: 9000
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/